"""
Sandbox service package

Submodules:
- concurrency: 数据类 + 并发限制器 + Token 管理
- base: Seccomp BPF + VFSBootstrap 注入代码 + FUSE 缓存检查
"""
from .concurrency import (
    SandboxConfig,
    ExecResult,
    BackgroundTask,
    SandboxConcurrencyLimiter,
    _global_concurrency_limiter,
    register_sandbox_token,
    unregister_sandbox_token,
    validate_sandbox_token,
    _cleanup_expired_tokens,
)
from .base import (
    SYS_READ, SYS_WRITE, SYS_OPEN, SYS_CLOSE, SYS_STAT, SYS_FSTAT, SYS_LSTAT,
    SYS_POLL, SYS_LSEEK, SYS_MMAP, SYS_MPROTECT, SYS_MUNMAP, SYS_BRK,
    SYS_RT_SIGACTION, SYS_RT_SIGPROCMASK, SYS_RT_SIGRETURN, SYS_IOCTL,
    SYS_PREAD64, SYS_PWRITE64, SYS_READV, SYS_WRITEV, SYS_ACCESS,
    SYS_PIPE, SYS_SELECT, SYS_SCHED_YIELD, SYS_MREMAP, SYS_MSYNC,
    SYS_MINCORE, SYS_MADVISE, SYS_SHMGET, SYS_SHMAT, SYS_SHMCTL, SYS_SHMDT,
    SYS_DUP, SYS_DUP2, SYS_NANOSLEEP, SYS_GETITIMER, SYS_SETITIMER,
    SYS_GETPID, SYS_SENDFILE, SYS_SOCKET, SYS_CONNECT, SYS_ACCEPT,
    SYS_SENDTO, SYS_RECVFROM, SYS_SENDMSG, SYS_RECVMSG, SYS_SHUTDOWN,
    SYS_BIND, SYS_LISTEN, SYS_GETSOCKNAME, SYS_GETPEERNAME,
    SYS_SETSOCKOPT, SYS_GETSOCKOPT, SYS_CLONE, SYS_EXECVE, SYS_EXIT,
    SYS_WAIT4, SYS_KILL, SYS_UNAME, SYS_FCNTL, SYS_FLOCK, SYS_FSYNC,
    SYS_FDATASYNC, SYS_TRUNCATE, SYS_FTRUNCATE, SYS_GETDENTS, SYS_GETCWD,
    SYS_CHDIR, SYS_FCHDIR, SYS_RENAME, SYS_MKDIR, SYS_RMDIR, SYS_CREAT,
    SYS_LINK, SYS_UNLINK, SYS_SYMLINK, SYS_READLINK, SYS_CHMOD, SYS_FCHMOD,
    SYS_CHOWN, SYS_FCHOWN, SYS_LCHOWN, SYS_UMASK, SYS_GETTIMEOFDAY,
    SYS_GETRUSAGE, SYS_SYSINFO, SYS_TIMES, SYS_GETUID, SYS_GETGID,
    SYS_GETEUID, SYS_GETEGID, SYS_GETPPID, SYS_GETPGID, SYS_GETTID,
    SYS_GETDENTS64, SYS_SET_TID_ADDRESS, SYS_FUTEX, SYS_CLOCK_GETTIME,
    SYS_CLOCK_GETRES, SYS_CLOCK_NANOSLEEP, SYS_EXIT_GROUP, SYS_EPOLL_WAIT,
    SYS_EPOLL_CTL, SYS_TGKILL, SYS_UTIMENSAT, SYS_SET_ROBUST_LIST,
    SYS_GET_ROBUST_LIST, SYS_SCHED_GETAFFINITY, SYS_SCHED_SETAFFINITY,
    SYS_SCHED_GETPARAM, SYS_SCHED_GETSCHEDULER, SYS_GETCPU, SYS_GETRANDOM,
    SYS_COPY_FILE_RANGE, SYS_GETGROUPS, SYS_SIGALTSTACK, SYS_MEMFD_CREATE,
    SYS_EVENTFD2, SYS_PIPE2, SYS_DUP3, SYS_OPENAT, SYS_MKDIRAT,
    SYS_UNLINKAT, SYS_RENAMEAT, SYS_LINKAT, SYS_SYMLINKAT, SYS_READLINKAT,
    SYS_FCHMODAT, SYS_FACCESSAT, SYS_PSELECT6, SYS_PPOLL, SYS_NEWFSTATAT,
    SYS_CLONE3, SYS_RSEQ, SYS_PERSONALITY, SYS_PRCTL, SYS_ARCH_PRCTL,
    SYS_SIGNALFD4, SYS_TIMERFD_CREATE, SYS_TIMERFD_SETTIME,
    SYS_TIMERFD_GETTIME, SYS_INOTIFY_INIT, SYS_INOTIFY_ADD_WATCH,
    SYS_INOTIFY_RM_WATCH, SYS_ACCEPT4, SYS_RECVMMSG, SYS_SENDMMSG,
    SYS_GETSID, SYS_SETSID, SYS_GETPGRP, SYS_PRLIMIT64, SYS_GETRLIMIT,
    SYS_SETRLIMIT, SYS_TIME,
    SECCOMP_RET_ALLOW, SECCOMP_RET_KILL, SECCOMP_RET_ERRNO, SECCOMP_RET_TRAP,
    EPERM, AUDIT_ARCH_X86_64,
    BPF_LD, BPF_JMP, BPF_RET, BPF_JEQ, BPF_W, BPF_ABS,
    _build_bpf, _create_seccomp_bpf,
    _SECCOMP_BPF, _SECCOMP_BPF_B64, _SECCOMP_SETUP_CODE,
    VFSBootstrap,
    _check_fuse_cached, _FUSE_AVAILABLE_CACHE,
)

__all__ = [
    "SandboxConfig", "ExecResult", "BackgroundTask",
    "SandboxConcurrencyLimiter", "_global_concurrency_limiter",
    "register_sandbox_token", "unregister_sandbox_token",
    "validate_sandbox_token", "_cleanup_expired_tokens",
    "VFSBootstrap",
    "_check_fuse_cached", "_FUSE_AVAILABLE_CACHE",
    "_SECCOMP_BPF", "_SECCOMP_BPF_B64", "_SECCOMP_SETUP_CODE",
]
